# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'vcr'

VCR.config do |c|
  c.allow_http_connections_when_no_cassette = true
  c.cassette_library_dir     = 'spec/cassettes'
  c.stub_with                :fakeweb
  c.default_cassette_options = { :record => :new_episodes }
end

RSpec.configure do |config|
  config.extend VCR::RSpec::Macros
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

def load_test_spreadsheets
  ProjectRadiatorReader::config[:project_radiator_key] = "0Ao0uXCuPaqQVdFl6UUJsOHh1NzRDczA4bTFFbzdQOEE"
  ProjectRadiatorReader::config[:progress_tracker_keys] = {
    "Menume" => "0Ao0uXCuPaqQVdEljRmVlWFZHUU54RnF2dkxsSlRwOHc",
    "Narrable" => "0Ao0uXCuPaqQVdGJnQjJNMDM2R1REWHg2ZkdXemdfY2c",
  }
end
